/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic = require('./code/customermessage-logic');

class sameer_2_a38Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    sameer_2_a38Srv
};